version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/server-entrypoint.sh
        volumes:
            - static_volume:/app/backend/static
        expose:
            - 8000     
        env_file:
            - ./backend/.env
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/backend/static
        env_file:
            - ./backend/.env
        depends_on:
            - server
            - redis
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./backend/.env
        expose:
            - 5432
    

volumes:
    static_volume: {}
    postgres_data: {}


# sudo docker-compose build && sudo docker-compose up // build and start
# sudo docker-compose up --build -d // start in detached mode
# sudo docker-compose up -d --no-deps --build server // for restart server-container
# sudo docker-compose down // stop