# Generated by Django 4.1.7 on 2023-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_field',
            field=models.CharField(default='string', max_length=255),
        ),
    ]
